<a href="https://colab.research.google.com/github/psygrammer/about_python_dl_from_scrach_2/blob/main/notebooks/ch03/ch03_word2vec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 3. word2vec

* 싸이그래머 / 어바웃파이썬 : 딥러닝 NLP [1]
* 김무성

# 차례 
* 3.1 추론 기반 기법과 신경망
  - 3.1.1 통계 기반 기법의 문제점
  - 3.1.2 추론 기반 기법 개요
  - 3.1.3 신경망에서의 단어 처리
* 3.2 단순한 word2vec
  - 3.2.1 CBOW 모델의 추론 처리
  - 3.2.2 CBOW 모델의 학습
  - 3.2.3 word2vec의 가중치와 분산 표현
* 3.3 학습 데이터 준비
  - 3.3.1 맥락과 타깃
  - 3.3.2 원핫 표현으로 변환
* 3.4 CBOW 모델 구현
  - 3.4.1 학습 코드 구현
* 3.5 word2vec 보충
  - 3.5.1 CBOW 모델과 확률
  - 3.5.2 skip-gram 모델
  - 3.5.3 통계 기반 vs. 추론 기반
* 3.6 정리

------------------

In [ ]:
!git clone https://github.com/psygrammer/about_python_dl_from_scrach_2.git

Cloning into 'about_python_dl_from_scrach_2'...
remote: Enumerating objects: 104, done.
remote: Counting objects: 100% (104/104), done.
remote: Compressing objects: 100% (88/88), done.
remote: Total 104 (delta 44), reused 33 (delta 5), pack-reused 0
Receiving objects: 100% (104/104), 746.54 KiB | 4.50 MiB/s, done.
Resolving deltas: 100% (44/44), done.


In [ ]:
ls

about_python_dl_from_scrach_2/  sample_data/


In [ ]:
cd /content/about_python_dl_from_scrach_2/notebooks/ch03

/content/about_python_dl_from_scrach_2/notebooks/ch03


In [ ]:
ls

ch03_word2vec_sol.ipynb


------------------------

# 3.1 추론 기반 기법과 신경망
* 3.1.1 통계 기반 기법의 문제점
* 3.1.2 추론 기반 기법 개요
* 3.1.3 신경망에서의 단어 처리

## 3.1.1 통계 기반 기법의 문제점


## 3.1.2 추론 기반 기법 개요


## 3.1.3 신경망에서의 단어 처리

In [ ]:
import numpy as np

In [ ]:
# 입력
c = # 실습 !!
c

array([[1, 0, 0, 0, 0, 0, 0]])

In [ ]:
# 가중치
# 랜덤 초기화
W = # 실습 !!
W

array([[-0.01408087, -1.70087336,  0.97747598],
       [ 0.62588852,  0.29016156,  1.20329955],
       [ 1.62648654,  0.48388702, -0.84231368],
       [-1.19646301, -0.24558409, -0.51263625],
       [-0.20585163,  0.0286256 ,  0.22099289],
       [-0.79984444,  1.04855367,  1.25478784],
       [ 0.24926519, -0.31154451,  1.38341062]])

In [ ]:
# 중간노드
h = # 실습 !! 
h

array([[-0.01408087, -1.70087336,  0.97747598]])

#### 위의 코드는 1장에서 구현한 MaMul 계층으로도 수행할 수 있다. 

In [ ]:
import sys
sys.path.append('..')

In [ ]:
import numpy as np
from common.layers import MatMul

In [ ]:
# 입력
c = # 실습 !!
c

array([[1, 0, 0, 0, 0, 0, 0]])

In [ ]:
# 가중치
# 랜덤 초기화
W = # 실습 !!
W

array([[ 1.29373618,  0.07850321,  1.23219806],
       [-0.83077307,  1.43327969,  0.77527253],
       [-0.32122274, -0.6751306 , -1.40619308],
       [-0.18549382, -2.15863886,  1.13753216],
       [-0.23515995,  0.76372041, -0.23065273],
       [-0.82121156, -0.18724179, -0.45392134],
       [-0.33732292, -0.85531403,  1.96969153]])

In [ ]:
layer = # 실습 !!
layer

In [ ]:
h = # 실습 !!
h

array([[1.29373618, 0.07850321, 1.23219806]])

-------------

# 3.2 단순한 word2vec
* 3.2.1 CBOW 모델의 추론 처리
* 3.2.2 CBOW 모델의 학습
* 3.2.3 word2vec의 가중치와 분산 표현


## 3.2.1 CBOW 모델의 추론 처리


In [ ]:
# coding: utf-8
import sys
sys.path.append('..')
import numpy as np
from common.layers import MatMul

In [ ]:
# 샘플 맥락 데이터
c0 = # 실습 !!
c1 = # 실습 !!

In [ ]:
# 가중치 초기화
W_in = # 실습 !!
W_out = # 실습 !!

In [ ]:
# 계층 생성
in_layer0 = # 실습 !!
in_layer1 = # 실습 !!
out_layer = # 실습 !!

In [ ]:
# 순전파
h0 = # 실습 !!
h1 = # 실습 !!
h = # 실습 !!
s = # 실습 !!
print(s)

[[-0.28504955  1.62074068  1.43591948 -1.71722792 -0.61956681 -0.09237032
   1.34068562]]


## 3.2.2 CBOW 모델의 학습


## 3.2.3 word2vec의 가중치와 분산 표현

--------------

# 3.3 학습 데이터 준비
* 3.3.1 맥락과 타깃
* 3.3.2 원핫 표현으로 변환


## 3.3.1 맥락과 타깃


In [ ]:
import sys
sys.path.append('..')  # 부모 디렉터리의 파일을 가져올 수 있도록 설정

In [ ]:
from common.util import preprocess

In [ ]:
text = 'You say goodbye and I say hello.'
corpus, word_to_id, id_to_word = preprocess(text)

In [ ]:
corpus

array([0, 1, 2, 3, 4, 1, 5, 6])

In [ ]:
word_to_id

{'.': 6, 'and': 3, 'goodbye': 2, 'hello': 5, 'i': 4, 'say': 1, 'you': 0}

In [ ]:
id_to_word

{0: 'you', 1: 'say', 2: 'goodbye', 3: 'and', 4: 'i', 5: 'hello', 6: '.'}

In [ ]:
def create_contexts_target(corpus, window_size=1):
    '''맥락과 타깃 생성
    :param corpus: 말뭉치(단어 ID 목록)
    :param window_size: 윈도우 크기(윈도우 크기가 1이면 타깃 단어 좌우 한 단어씩이 맥락에 포함)
    :return:
    '''
    target = corpus[window_size:-window_size]
    contexts = []

    for idx in range(window_size, len(corpus)-window_size):
        cs = []
        for t in range(-window_size, window_size + 1):
            if t == 0:
                continue
            cs.append(corpus[idx + t])
        contexts.append(cs)

    return np.array(contexts), np.array(target)

In [ ]:
context, target = create_contexts_target(corpus, window_size=1)

In [ ]:
context

array([[0, 2],
       [1, 3],
       [2, 4],
       [3, 1],
       [4, 5],
       [1, 6]])

In [ ]:
target

array([1, 2, 3, 4, 1, 5])

## 3.3.2 원핫 표현으로 변환

In [ ]:
def convert_one_hot(corpus, vocab_size):
    '''원핫 표현으로 변환
    :param corpus: 단어 ID 목록(1차원 또는 2차원 넘파이 배열)
    :param vocab_size: 어휘 수
    :return: 원핫 표현(2차원 또는 3차원 넘파이 배열)
    '''
    N = corpus.shape[0]

    if corpus.ndim == 1:
        one_hot = np.zeros((N, vocab_size), dtype=np.int32)
        for idx, word_id in enumerate(corpus):
            one_hot[idx, word_id] = 1

    elif corpus.ndim == 2:
        C = corpus.shape[1]
        one_hot = np.zeros((N, C, vocab_size), dtype=np.int32)
        for idx_0, word_ids in enumerate(corpus):
            for idx_1, word_id in enumerate(word_ids):
                one_hot[idx_0, idx_1, word_id] = 1

    return one_hot

In [ ]:
vocab_size = len(word_to_id)
vocab_size

7

In [ ]:
target = convert_one_hot(target, vocab_size)
target

array([[[0, 1, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0]],

       [[1, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0]],

       [[1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0]],

       [[1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0]],

       [[1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],


In [ ]:
context = convert_one_hot(context, vocab_size)
context

array([[[1, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0]],

       [[0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0]],

       [[0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0]],

       [[0, 0, 0, 1, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 1, 0]],

       [[0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1]]], dtype=int32)

--------------

# 3.4 CBOW 모델 구현
* 3.4.1 학습 코드 구현


## 3.4.1 학습 코드 구현

-----------------

# 3.5 word2vec 보충
* 3.5.1 CBOW 모델과 확률
* 3.5.2 skip-gram 모델
* 3.5.3 통계 기반 vs. 추론 기반


## 3.5.1 CBOW 모델과 확률


## 3.5.2 skip-gram 모델


## 3.5.3 통계 기반 vs. 추론 기반

-----------------

# 3.6 정리

------------------
# 참고문헌
* [1] 밑바닥부터 시작하는 딥러닝 2
  - https://www.hanbit.co.kr/store/books/look.php?p_code=B8950212853
  - github - https://github.com/WegraLee/deep-learning-from-scratch-2