<a href="https://colab.research.google.com/github/psygrammer/about_python_dl_from_scrach_2/blob/main/notebooks/ch04/ch04_word2vec_more.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 4 word2vec 속도 개선 

* 싸이그래머 / 어바웃파이썬 : 딥러닝 NLP [1]
* 김무성

----------------

# 차례 
* 4.1 word2vec 개선 ①
  - 4.1.1 Embedding 계층
  - 4.1.2 Embedding 계층 구현
* 4.2 word2vec 개선 ②
  - 4.2.1 은닉층 이후 계산의 문제점
  - 4.2.2 다중 분류에서 이진 분류로
  - 4.2.3 시그모이드 함수와 교차 엔트로피 오차
  - 4.2.4 다중 분류에서 이진 분류로(구현)
  - 4.2.5 네거티브 샘플링
  - 4.2.6 네거티브 샘플링의 샘플링 기법
  - 4.2.7 네거티브 샘플링 구현
* 4.3 개선판 word2vec 학습
  - 4.3.1 CBOW 모델 구현
  - 4.3.2 CBOW 모델 학습 코드
  - 4.3.3 CBOW 모델 평가 
* 4.4 word2vec 남은 주제
  - 4.4.1 word2vec을 사용한 애플리케이션의 예
  - 4.4.2 단어 벡터 평가 방법
* 4.5 정리

-------------------

In [1]:
!git clone https://github.com/psygrammer/about_python_dl_from_scrach_2.git

Cloning into 'about_python_dl_from_scrach_2'...
remote: Enumerating objects: 149, done.
remote: Counting objects: 100% (149/149), done.
remote: Compressing objects: 100% (133/133), done.
remote: Total 149 (delta 64), reused 33 (delta 5), pack-reused 0
Receiving objects: 100% (149/149), 786.83 KiB | 2.95 MiB/s, done.
Resolving deltas: 100% (64/64), done.


In [2]:
ls

about_python_dl_from_scrach_2/  sample_data/


In [4]:
cd /content/about_python_dl_from_scrach_2/notebooks/ch04

/content/about_python_dl_from_scrach_2/notebooks/ch04


In [5]:
ls

ch04_word2vec_more_sol.ipynb


# 4.1 word2vec 개선 ①
  - 4.1.1 Embedding 계층
  - 4.1.2 Embedding 계층 구현

## 4.1.1 Embedding 계층


## 4.1.2 Embedding 계층 구현

In [6]:
import numpy as np

In [7]:
W = np.arange(21).reshape(7,3)

In [8]:
W

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [9]:
# 실습 !!

array([6, 7, 8])

In [10]:
# 실습 !!

array([15, 16, 17])

In [11]:
idx = # 실습 !!
W[idx]

array([[ 3,  4,  5],
       [ 0,  1,  2],
       [ 9, 10, 11],
       [ 0,  1,  2]])

In [15]:
class Embedding:
  def __init__(self, W):
    # 실습 !!
  
  def forward(self, idx):
    # 실습 !!

In [16]:
emb = Embedding(W)

In [17]:
out = emb.forward(idx)
out

array([[ 3,  4,  5],
       [ 0,  1,  2],
       [ 9, 10, 11],
       [ 0,  1,  2]])

------------------

# 4.2 word2vec 개선 ②
  - 4.2.1 은닉층 이후 계산의 문제점
  - 4.2.2 다중 분류에서 이진 분류로
  - 4.2.3 시그모이드 함수와 교차 엔트로피 오차
  - 4.2.4 다중 분류에서 이진 분류로(구현)
  - 4.2.5 네거티브 샘플링
  - 4.2.6 네거티브 샘플링의 샘플링 기법
  - 4.2.7 네거티브 샘플링 구현

## 4.2.1 은닉층 이후 계산의 문제점


## 4.2.2 다중 분류에서 이진 분류로


## 4.2.3 시그모이드 함수와 교차 엔트로피 오차


## 4.2.4 다중 분류에서 이진 분류로(구현)


## 4.2.5 네거티브 샘플링


## 4.2.6 네거티브 샘플링의 샘플링 기법


## 4.2.7 네거티브 샘플링 구현

-----------------

# 4.3 개선판 word2vec 학습
  - 4.3.1 CBOW 모델 구현
  - 4.3.2 CBOW 모델 학습 코드
  - 4.3.3 CBOW 모델 평가 


## 4.3.1 CBOW 모델 구현


## 4.3.2 CBOW 모델 학습 코드


## 4.3.3 CBOW 모델 평가

-----------------

# 4.4 word2vec 남은 주제
  - 4.4.1 word2vec을 사용한 애플리케이션의 예
  - 4.4.2 단어 벡터 평가 방법


## 4.4.1 word2vec을 사용한 애플리케이션의 예


## 4.4.2 단어 벡터 평가 방법

----------------

# 4.5 정리

------------------
# 참고문헌
* [1] 밑바닥부터 시작하는 딥러닝 2
  - https://www.hanbit.co.kr/store/books/look.php?p_code=B8950212853
  - github - https://github.com/WegraLee/deep-learning-from-scratch-2