<a href="https://colab.research.google.com/github/psygrammer/about_python_dl_from_scrach_2/blob/main/notebooks/ch02/ch02_nlp_and_word_distributional_representation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2. 자연어와 단어의 분산 표현 

1.   항목 추가
2.   항목 추가



* 싸이그래머 / 어바웃파이썬 : 딥러닝 NLP [1]
* 김무성

--------------

# 차례 
* 2.1 자연어처리란
  - 2.1.1 단어의 의미
* 2.2 시소러스
  - 2.2.1 WordNet
  - 2.2.2 시소러스의 문제점
* 2.3 통계 기반 기법
  - 2.3.1 파이썬으로 말뭉치 전처리하기
  - 2.3.2 단어의 분산 표현
  - 2.3.3 분포 가설
  - 2.3.4 동시발생 행렬
  - 2.3.5 벡터 간 유사도
  - 2.3.6 유사 단어의 랭킹 표시
* 2.4 통계 기반 기법 개선하기
  - 2.4.1 상호정보량
  - 2.4.2 차원 감소
  - 2.4.3 SVD에 의한 차원 감소
  - 2.4.4 PTB 데이터셋
  - 2.4.5 PTB 데이터셋 평가
* 정리

------------

In [ ]:
!git clone https://github.com/psygrammer/about_python_dl_from_scrach_2.git

Cloning into 'about_python_dl_from_scrach_2'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 26 (delta 8), reused 10 (delta 2), pack-reused 0
Unpacking objects: 100% (26/26), done.


In [ ]:
ls

about_python_dl_from_scrach_2/  sample_data/


In [ ]:
cd /content/about_python_dl_from_scrach_2/notebooks/ch02

/content/about_python_dl_from_scrach_2/notebooks/ch02


In [ ]:
ls

ch02_nlp_and_word_distributional_representation.ipynb


# 2.1 자연어처리란
* 2.1.1 단어의 의미

## 2.1.1 단어의 의미

------------

# 2.2 시소러스
* 2.2.1 WordNet
* 2.2.2 시소러스의 문제점


## 2.2.1 WordNet


## 2.2.2 시소러스의 문제점


--------------

# 2.3 통계 기반 기법
* 2.3.1 파이썬으로 말뭉치 전처리하기
* 2.3.2 단어의 분산 표현
* 2.3.3 분포 가설
* 2.3.4 동시발생 행렬
* 2.3.5 벡터 간 유사도
* 2.3.6 유사 단어의 랭킹 표시

 ## 2.3.1 파이썬으로 말뭉치 전처리하기
 

In [ ]:
text = 'You say goodbye and I say hello.'

In [ ]:
text = text.lower()
text

'you say goodbye and i say hello.'

In [ ]:
text = text.replace('.', ' .')
text

'you say goodbye and i say hello .'

In [ ]:
words = text.split(' ')
words

['you', 'say', 'goodbye', 'and', 'i', 'say', 'hello', '.']

In [ ]:
word_to_id = {}

In [ ]:
id_to_word = {}

In [ ]:
for word in words:
  if word not in word_to_id:
    new_id = len(word_to_id)
    word_to_id[word] = new_id
    id_to_word[new_id] = word

In [ ]:
word_to_id

{'.': 6, 'and': 3, 'goodbye': 2, 'hello': 5, 'i': 4, 'say': 1, 'you': 0}

In [ ]:
id_to_word

{0: 'you', 1: 'say', 2: 'goodbye', 3: 'and', 4: 'i', 5: 'hello', 6: '.'}

In [ ]:
id_to_word[1]

'say'

In [ ]:
word_to_id['hello']

5

In [ ]:
import numpy as np

In [ ]:
corpus = [word_to_id[w] for w in words]
corpus

[0, 1, 2, 3, 4, 1, 5, 6]

In [ ]:
corpus = np.array(corpus)
corpus

array([0, 1, 2, 3, 4, 1, 5, 6])

In [ ]:
# 지금까지의 처리들을 한 데 모아 하나의 함수로
def preprocess(text):
  text = text.lower()
  text = text.replace('.', ' .')
  words = text.split(' ')

  word_to_id = {}
  id_to_word = {}

  for word in words:
    if word not in word_to_id:
      new_id = len(word_to_id)
      word_to_id[word] = new_id
      id_to_word[new_id] = word

  
  corpus = np.array([word_to_id[w] for w in words])

  return corpus, word_to_id, id_to_word

In [ ]:
text = 'You say goodbye and I say hello.'
corpus, word_to_id, id_to_word = preprocess(text)
print(corpus)
print(word_to_id)
print(id_to_word)

[0 1 2 3 4 1 5 6]
{'you': 0, 'say': 1, 'goodbye': 2, 'and': 3, 'i': 4, 'hello': 5, '.': 6}
{0: 'you', 1: 'say', 2: 'goodbye', 3: 'and', 4: 'i', 5: 'hello', 6: '.'}


In [ ]:
# util.py 라는 파일을 만들어서 preprocess를 해당 파일로 분리해놓고 써보자
import util

In [ ]:
text = 'You say goodbye and I say hello.'
corpus, word_to_id, id_to_word = util.preprocess(text)
print(corpus)
print(word_to_id)
print(id_to_word)

## 2.3.2 단어의 분산 표현
 

## 2.3.3 분포 가설
 

## 2.3.4 동시발생 행렬
 

In [ ]:
import numpy as np
from util import preprocess

In [ ]:
text = 'You say goodbye and I say hello.'
corpus, word_to_id, id_to_word = preprocess(text)

print(corpus)
print(id_to_word)

[0 1 2 3 4 1 5 6]
{0: 'you', 1: 'say', 2: 'goodbye', 3: 'and', 4: 'i', 5: 'hello', 6: '.'}


In [ ]:
# 동시발생 행렬 예시
C = np.array([
  [0, 1, 0, 1, 0, 0, 0],
  [0, 0, 1, 0, 1, 0, 0],
  [0, 1, 0, 1, 0, 0, 0],
  [0, 1, 0, 0, 0, 0, 1],
  [0, 0, 0, 0, 0, 1, 0],              
], dtype=np.int32)

print(type(C))
print(C)

<class 'numpy.ndarray'>
[[0 1 0 1 0 0 0]
 [0 0 1 0 1 0 0]
 [0 1 0 1 0 0 0]
 [0 1 0 0 0 0 1]
 [0 0 0 0 0 1 0]]


In [ ]:
# ID가 0인 단어의 벡터 표현
print(C[0])

[0 1 0 1 0 0 0]


In [ ]:
# ID가 4인 단어의 벡터 표현
print(C[4])

[0 0 0 0 0 1 0]


In [ ]:
# 'goodbye'의 벡터 표현
print(C[word_to_id['goodbye']])

[0 1 0 1 0 0 0]


In [ ]:
# 말뭉치로부터 동시발생 행렬을 만들어주는 함수를 구현해보자.
# 그리고 util.py 파일에 함수 추가해주자.
def create_co_matrix(corpus, vocab_size, window_size=1):
  corpus_size = len(corpus)
  co_matrix = np.zeros((vocab_size, vocab_size), dtype=np.int32)

  for idx, word_id in enumerate(corpus):
    for i in range(1, window_size+1):
      left_idx = idx - i
      right_idx = idx + i

      if left_idx >= 0:
        left_word_id = corpus[left_idx]
        co_matrix[word_id, left_word_id] += 1

      if right_idx < corpus_size:
        right_word_id = corpus[right_idx]
        co_matrix[word_id, right_word_id] += 1

  return co_matrix


In [ ]:
len(word_to_id)

7

In [ ]:
vocab_size = len(word_to_id)
co_matrix = create_co_matrix(corpus, vocab_size, window_size=1)

print(co_matrix)

[[0 1 0 0 0 0 0]
 [1 0 1 0 1 1 0]
 [0 1 0 1 0 0 0]
 [0 0 1 0 1 0 0]
 [0 1 0 1 0 0 0]
 [0 1 0 0 0 0 1]
 [0 0 0 0 0 1 0]]


## 2.3.5 벡터 간 유사도

In [ ]:
# 코사인 유사도 함수 만들기 (그리고 util.py 파일에 추가)
def cos_similarity(x, y):
  nx = x / np.sqrt(np.sum(x**2)) # x의 정규화
  ny = y / np.sqrt(np.sum(y**2)) # y의 정규화
  return np.dot(nx, ny)


In [ ]:
C = create_co_matrix(corpus, vocab_size)
print(C)

[[0 1 0 0 0 0 0]
 [1 0 1 0 1 1 0]
 [0 1 0 1 0 0 0]
 [0 0 1 0 1 0 0]
 [0 1 0 1 0 0 0]
 [0 1 0 0 0 0 1]
 [0 0 0 0 0 1 0]]


In [ ]:
word_to_id

{'.': 6, 'and': 3, 'goodbye': 2, 'hello': 5, 'i': 4, 'say': 1, 'you': 0}

In [ ]:
c0 = C[word_to_id['you']]
c1 = C[word_to_id['i']]
print(c0)
print(c1)

[0 1 0 0 0 0 0]
[0 1 0 1 0 0 0]


## 2.3.6 유사 단어의 랭킹 표시


In [ ]:
# 유사 단어의 랭킹 표시 함수
def most_similar(query, word_to_id, id_to_word, word_matrix, top=5):
  # 검색어를 꺼낸ㄴ다
  if query not in word_to_id:
    print("%s(을)를 찾을 수 없습니다." % query)
    return

  print('\n[query] ' + query)
  query_id = word_to_id[query]
  query_vec = word_matrix[query_id]

  # 코사인 유사도 계산
  vocab_size = len(id_to_word)
  similarity = np.zeros(vocab_size)
  for i in range(vocab_size):
    similarity[i] = cos_similarity(word_matrix[i], query_vec)

  # 코사인 유사도를 기준으로 내림차순으로 출력
  count = 0
  for i in (-1*similarity).argsort():
    if id_to_word[i] == query:
      continue
    print(' %s: %s' %(id_to_word[i], similarity[i]))

    count += 1
    if count >= top:
      return

In [ ]:
most_similar('you', word_to_id, id_to_word, C, top=5)


[query] you
 goodbye: 0.7071067811865475
 i: 0.7071067811865475
 hello: 0.7071067811865475
 say: 0.0
 and: 0.0


----------------

# 2.4 통계 기반 기법 개선하기
* 2.4.1 상호정보량
* 2.4.2 차원 감소
* 2.4.3 SVD에 의한 차원 감소
* 2.4.4 PTB 데이터셋
* 2.4.5 PTB 데이터셋 평가


## 2.4.1 상호정보량


## 2.4.2 차원 감소


## 2.4.3 SVD에 의한 차원 감소


## 2.4.4 PTB 데이터셋


## 2.4.5 PTB 데이터셋 평가


---------

# 정리

------------------
# 참고문헌
* [1] 밑바닥부터 시작하는 딥러닝 2
  - https://www.hanbit.co.kr/store/books/look.php?p_code=B8950212853
  - github - https://github.com/WegraLee/deep-learning-from-scratch-2